#!/bin/sh

# install salt
if ! type salt &> /dev/null
then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -q
  apt-get install -qy apt-transport-https
  echo "deb https://repo.saltstack.com/apt/debian/8/amd64/latest jessie main" > /etc/apt/sources.list.d/saltstack.list
  wget -O - https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
  echo 'APT::Default-Release "jessie";' > /etc/apt/apt.conf.d/10apt
  echo "deb https://httpredir.debian.org/debian stretch main" > /etc/apt/sources.list.d/debian-stretch.list
  apt-get update -q
  apt-get install -qy salt-master salt-minion salt-cloud python-pygit2/stretch
fi

# create git ssh key
secretGitKeyPath="$HOME/.ssh/infra-secrets"
if ! test -e "${secretGitKeyPath}"
then
  ssh-keygen -t rsa -b 4096 -N "" -C "salt-master@infra-secrets" -f "${secretGitKeyPath}"
fi

# setup salt master and minon
timeout 5 salt-call test.ping > /dev/null
if test "$?" -ne "0"
then
  # point salt dns name to localhost
  grep -q -F '127.0.0.1 salt' /etc/hosts || echo '127.0.0.1 salt' >> /etc/hosts

  # wait for salt minion to start
  sleep 45

  # add minion key of master
  minionFingerprint=$(salt-call --local key.finger | head -n 2 | tail -n 1 | xargs)
  minionName=$(salt-key -F | grep "${minionFingerprint}" | head -n 1 | tail -n 1 | cut -d ":" -f "1" | xargs)
  salt-key -y -a "${minionName}"

  cat > /etc/salt/master <<EOF
hash_type: sha256
fileserver_backend:
  - git
gitfs_provider: pygit2
gitfs_remotes:
  - git://github.com/ahdinosaur/infra.git
git_pillar_provider: pygit2
ext_pillar:
  - git:
    - master git@github.com:ahdinosaur/infra-secrets.git:
      - privkey: ${secretGitKeyPath}
      - pubkey: ${secretGitKeyPath}.pub
EOF

  cat > /etc/salt/minion <<EOF
grains:
  roles:
    - salt-master
EOF

  salt-run fileserver.update
  salt '*' saltutil.refresh_pillar
  salt $(hostname) ssh.set_known_host user=root hostname=github.com
fi

# output ssh key
if test -e "${secretGitKeyPath}"
then
  cat "${secretGitKeyPath}"
  cat "${secretGitKeyPath}.pub"
fi
